
version: "3.9"
services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started


  api:
    build:
      context: .
    ports:
      - 8000:80
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py manage.py makemigrations && python manage.py manage.py migrate

  postgres:
      image: postgres:latest
      env_file: .env
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

      volumes:
        - /var/lib/docker/volumes/pg_data

