
version: "3.9"
services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
  api:
    image: artemiystepanov/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8000:80
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./docker_config.py:/code/default_config.py
  migrations:
    image: artemiystepanov/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py manage.py makemigrations && python manage.py manage.py migrate
    volumes:
      - ./docker_config.py:/code/default_config.py
  postgres:
      image: postgres:latest
      env_file: .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

      volumes:
        - ./pg_data:/var/lib/docker/volumes/data