# Generated by Django 4.2.2 on 2023-07-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_alter_goal_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Описание"
            ),
        ),
    ]
