# Generated by Django 4.2.2 on 2023-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="tg_user_id",
            field=models.IntegerField(unique=True),
        ),
    ]
