# Generated by Django 4.2.2 on 2023-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_tguser_first_name_tguser_last_name_tguser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="verification_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
