name: Build and deploy action
on: [push]
jobs:
  build_and_puch:
    runs-on: ubuntu-latest
    steps:
      #Логируем копирование кода
      - name: list dir
        run: ls -la
      # Копируем код из репозитория в runner
      - name: clone code
        uses: actions/checkout@v2
      #Логируем копирование кода
      - name: list dir
        run: ls -la
      # Собираем
      - name: docker build
        run: docker build -t artemiystepanov/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      #Заходим в аккаунт Docker
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #Отправляем в Docker hub
      - name: docker push
        run: docker push artemiystepanov/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
          cat doc